[package]
name = "fq2fa"
version = "0.1.0"
authors = ["wenjie1991 <sunwjie@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
